services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: securestack_juice_shop
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - lab_net

networks:
  lab_net:
    driver: bridge
